
vim.cmd([[let mapleader ="\<Space>"]])
vim.keymap.set('n', "<Space>", "<NOP>")
vim.keymap.set('i', '<S-Tab>', [[pumvisible() ? '\<C-p>' : '\<S-Tab>']], { silent = true, expr = true })
vim.keymap.set('i', '<Tab>', [[pumvisible() ? '\<C-n>' : '\<Tab>']], { silent = true, expr = true })
vim.keymap.set('n', '<leader>d', '"_d')
vim.keymap.set('v', '<leader>d', '"_d')
vim.keymap.set('v', '<leader>p', '"_dP')
------------------------------------------------------------------
vim.keymap.set('n', '<leader><leader>', ':WhichKey<CR>', { silent = true })
vim.keymap.set('n', '<leader>J', ':resize -2<CR>', { silent = true })
vim.keymap.set('n', '<leader>K', ':resize +2<CR>', { silent = true })
vim.keymap.set('n', '<leader>H', ':vertical resize +2<CR>', { silent = true })
vim.keymap.set('n', '<leader>L', ':vertical resize -2<CR>', { silent = true })
vim.keymap.set('n', '<leader>j', '<C-W>j', { silent = true })
vim.keymap.set('n', '<leader>k', '<C-W>k', { silent = true })
vim.keymap.set('n', '<leader>h', '<C-W>h', { silent = true })
vim.keymap.set('n', '<leader>l', '<C-W>l', { silent = true })
--Buffer
vim.keymap.set('n', '<leader><Tab>', ':BufferNext<CR>')
vim.keymap.set('n', '<leader><S-Tab>', ':BufferPrevious<CR>')
vim.keymap.set('n', '<leader>q', ':BufferClose<CR>')
vim.keymap.set('n', '<leader>qa', ':BufferCloseAllButCurrentOrPinned<CR>')
vim.keymap.set('n', '<leader>;', ':BufferPick<CR>')
vim.keymap.set('n', '<leader><Tab><Tab>', ':BufferPin<CR>')
--Window
vim.keymap.set('n', '<leader>sh', ':sp<CR>')
vim.keymap.set('n', '<leader>sv', ':vs<CR>')
vim.keymap.set('n', '<leader>ws', '<Cmd>WinShift<CR>')
--NvimTree
vim.keymap.set('n', '<leader>e', ':NvimTreeToggle<CR>')
vim.keymap.set('n', '<leader>er', ':NvimTreeRefresh<CR>')
vim.keymap.set('n', '<leader>ef', ':NvimTreeFindFile<CR>')
vim.keymap.set('n', '<leader>em', ':help nvim-tree.view.mappings<CR>')
--Telescope
vim.keymap.set('n', '<leader>t',  '<cmd>Telescope<CR>')
vim.keymap.set('n', '<leader>tb', function () require('telescope').builtin.buffers() end)
vim.keymap.set('n', '<leader>tf', function () require('telescope').builtin.find_files() end)
vim.keymap.set('n', '<leader>tg', function () require('telescope').builtin.live_grep() end)
vim.keymap.set('n', '<leader>th', function () require('telescope').builtin.help_tags() end)
vim.keymap.set('n', '<leader>td', function () require('telescope').builtin.diagnostics() end)
--LSP
vim.keymap.set('n', 'K', function() vim.lsp.buf.hover() end)
vim.keymap.set('n', '<leader>ga', function() vim.lsp.buf.code_action() end)
vim.keymap.set('n', '<leader>gd', function() vim.lsp.buf.definition() end)
vim.keymap.set('n', '<leader>gdc', function() vim.lsp.buf.declaration() end)
vim.keymap.set('n', '<leader>gf', function() vim.lsp.buf.format() end)
vim.keymap.set('n', '<leader>gfa', function() vim.lsp.buf.add_workspace_folder() end)
vim.keymap.set('n', '<leader>gi', function() vim.lsp.buf.implementation() end)
vim.keymap.set('n', '<leader>gk', function() vim.lsp.buf.signature_help() end)
vim.keymap.set('n', '<leader>glf', function() print(vim.inspect(vim.lsp.buf.list_workspace_folders())) end)
vim.keymap.set('n', '<leader>gr', function() vim.lsp.buf.references() end)
vim.keymap.set('n', '<leader>grf', function() vim.lsp.buf.remove_workspace_folder() end)
vim.keymap.set('n', '<leader>grn', function() vim.lsp.buf.rename() end)
vim.keymap.set('n', '<leader>gt', function() vim.lsp.buf.type_definition() end)
--DAP
vim.keymap.set('n', '<S-F5>', function() require('dap').run_last() end, { noremap = true, silent = true })
vim.keymap.set('n', '<F5>', function() require('dap').continue() end, { noremap = true, silent = true })
vim.keymap.set('n', '<F10>', function() require('dap').step_over() end, { noremap = true, silent = true })
vim.keymap.set('n', '<F11>', function() require('dap').step_into() end, { noremap = true, silent = true })
vim.keymap.set('n', '<F12>', function() require('dap').step_out() end, { noremap = true, silent = true })
vim.keymap.set('n', '<F9>', function() require('dap').toggle_breakpoint() end, { noremap = true, silent = true })
vim.keymap.set('n', '<S-F9>', function() require('dap').set_breakpoint(vim.fn.input('Breakpoint condition: ')) end, { noremap = true, silent = true })
vim.keymap.set('n', '<Leader>dr', function() require'dap'.repl.open() end, { noremap = true, silent = true })
--Terminal
vim.keymap.set('t', '<Esc>', '<C-\\><C-n>')
vim.keymap.set('n', '<Leader>`', ':ToggleTerm<CR>')
