# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.40.0"
"rocks-git.nvim" = "2.2.0"
"rocks-lazy.nvim" = "1.0.1"
"rocks-treesitter.nvim" = "1.1.2"
"copilot.lua" = {version = "scm", cmd = "Copilot", event = "InsertEnter"}
"image.nvim" = "1.3.0"
"markview.nvim" = "23.0.0"
"mason-lspconfig.nvim" = "1.31.0"
"mason.nvim" = "1.10.0"
"mini.clue" = "0.13.0"
"mini.diff" = "0.13.0"
"mini.extra" = "0.13.0"
"mini.files" = "0.13.0"
"mini.icons" = "scm"
"mini.notify" = "0.13.0"
"mini.nvim" = "0.9.0"
"mini.pick" = "0.13.0"
"mini.statusline" = "0.9.0"
"neodev.nvim" = "3.0.0"
"none-ls.nvim" = "scm"
"plenary.nvim" = "scm"
nvim-lspconfig = "0.1.8"
nvim-treesitter = "scm"
nvim-treesitter-context = "scm"
nvim-treesitter-textobjects = "scm"
tree-sitter-angular = "scm"
tree-sitter-bash = "scm"
tree-sitter-c = "scm"
tree-sitter-c_sharp = "scm"
tree-sitter-diff = "scm"
tree-sitter-html = "scm"
tree-sitter-json = "scm"
tree-sitter-latex = "scm"
tree-sitter-lua = "scm"
tree-sitter-luadoc = "scm"
tree-sitter-markdown = "scm"
tree-sitter-markdown_inline = "scm"
tree-sitter-python = "scm"
tree-sitter-requirements = "scm"
tree-sitter-toml = "scm"
tree-sitter-vim = "scm"
tree-sitter-vimdoc = "scm"
"rocks-config.nvim" = "2.2.0"

[plugins."markdown-preview.nvim"]
git = "iamcco/markdown-preview.nvim"
rev = "v0.0.9^{}"
build = "cd app && npm install"

[plugins.catppuccin ]
git = "catppuccin/nvim"
rev = "v1.9.0"

[plugins.mason-null-ls ]
git = "jay-babu/mason-null-ls.nvim"
rev = "v2.6.0"

[plugins.molten-nvim ]
git = "benlubas/molten-nvim"
rev = "v1.8.5"

[plugins.neorg ]
git = "nvim-neorg/neorg"
rev = "v9.1.1"

[plugins.vimtex]
git = "lervag/vimtex"
rev = "v2.9"
