# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.44.0"
"rocks-config.nvim" = "3.1.0"
"rocks-git.nvim" = "2.5.3"
"rocks-lazy.nvim" = "1.2.0"
"rocks-treesitter.nvim" = "1.3.0"
"copilot.lua" = "scm"
"diffview.nvim" = "scm"
"image.nvim" = "1.3.0"
"lazydev.nvim" = "1.9.0"
"markview.nvim" = "25.7.0"
"mini.nvim" = "scm"
"none-ls.nvim" = "scm"
"plenary.nvim" = "scm"
"which-key.nvim" = "3.17.0"
"mason.nvim" = "scm"
"mason-lspconfig.nvim" = "scm"
neogit = "scm"
nvim-dap = "0.10.0"
nvim-dap-virtual-text = "scm"
nvim-lspconfig = "2.1.0"
nvim-nio = "1.10.1"
nvim-treesitter-context = "scm"
nvim-treesitter-textobjects = "scm"
tree-sitter-angular = "scm"
tree-sitter-bash = "scm"
tree-sitter-c = "scm"
tree-sitter-c_sharp = "0.0.41"
tree-sitter-csv = "0.0.29"
tree-sitter-diff = "scm"
tree-sitter-html = "scm"
tree-sitter-json = "scm"
tree-sitter-latex = "scm"
tree-sitter-lua = "scm"
tree-sitter-luadoc = "scm"
tree-sitter-markdown = "scm"
tree-sitter-markdown_inline = "scm"
tree-sitter-python = "0.0.46"
tree-sitter-requirements = "scm"
tree-sitter-toml = "scm"
tree-sitter-vim = "scm"
tree-sitter-vimdoc = "scm"

[plugins."markdown-preview.nvim"]
git = "iamcco/markdown-preview.nvim"
rev = "v0.0.10"
build = "cd app && npm install"

[plugins.catppuccin]
git = "catppuccin/nvim"
rev = "v1.10.0"

[plugins.molten-nvim]
git = "benlubas/molten-nvim"
rev = "v1.9.2"

[plugins.neorg]
git = "nvim-neorg/neorg"
rev = "v9.3.0"

[plugins.vimtex]
git = "lervag/vimtex"
rev = "v2.16"

[plugins."blink.cmp"]
git = "Saghen/blink.cmp"
rev = "v1.2.0"

[plugins.quarto-nvim]
git = "quarto-dev/quarto-nvim"
rev = "v1.2.4"

[plugins."otter.nvim"]
git = "jmbuhr/otter.nvim"
rev = "v2.11.2"

[plugins."jupytext.nvim"]
git = "GCBallesteros/jupytext.nvim"
rev = "c8baf3ad344c59b3abd461ecc17fc16ec44d0f7b"

[plugins."img-clip.nvim"]
git = "HakonHarnes/img-clip.nvim"
rev = "v0.6.0"

[plugins."apidocs.nvim"]
git = "emmanueltouzery/apidocs.nvim"
rev = "0a551c63f95e00de2d662cb889a198beb5a3af27"

[plugins."debugmaster.nvim"]
git = "https://github.com/miroshQa/debugmaster.nvim"
rev = "7019f36d47079281c11f7ab5edb1cd1f23499fb8"

[plugins."easy-dotnet.nvim"]
git = "https://github.com/GustavEikaas/easy-dotnet.nvim"
rev = "50e3d11c16ef80df475e0c92248cdc066bc9fc0a"

[treesitter]
auto_install = "prompt" # true | false

[config]
plugins_dir = "plugins/"
auto_setup = false
