# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.43.0"
"rocks-git.nvim" = "2.5.2"
"rocks-lazy.nvim" = "1.1.1"
"rocks-treesitter.nvim" = "1.3.0"
"copilot.lua" = "scm"
"image.nvim" = "1.3.0"
"lazydev.nvim" = "1.9.0"
"markview.nvim" = "24.0.0"
"mason-lspconfig.nvim" = "scm"
"mason.nvim" = "scm"
"mini.nvim" = "scm"
"none-ls.nvim" = "scm"
"plenary.nvim" = "scm"
"rocks-config.nvim" = "3.1.0"
neogit = "scm"
nvim-lspconfig = "1.3.0"
nvim-treesitter = "scm"
nvim-treesitter-context = "scm"
nvim-treesitter-textobjects = "scm"
tree-sitter-angular = "scm"
tree-sitter-bash = "scm"
tree-sitter-c = "scm"
tree-sitter-c_sharp = "scm"
tree-sitter-diff = "scm"
tree-sitter-html = "scm"
tree-sitter-json = "scm"
tree-sitter-latex = "scm"
tree-sitter-lua = "scm"
tree-sitter-luadoc = "scm"
tree-sitter-markdown = "scm"
tree-sitter-markdown_inline = "scm"
tree-sitter-python = "scm"
tree-sitter-requirements = "scm"
tree-sitter-toml = "scm"
tree-sitter-vim = "scm"
tree-sitter-vimdoc = "scm"
"diffview.nvim" = "scm"
tree-sitter-csv = "0.0.29"
"which-key.nvim" = "3.15.0"

[plugins."markdown-preview.nvim"]
git = "iamcco/markdown-preview.nvim"
rev = "v0.0.10"
build = "cd app && npm install"

[plugins.catppuccin ]
git = "catppuccin/nvim"
rev = "v1.9.0"

[plugins.mason-null-ls ]
git = "jay-babu/mason-null-ls.nvim"
rev = "v2.6.0"

[plugins.molten-nvim ]
git = "benlubas/molten-nvim"
rev = "v1.9.1"

[plugins.neorg ]
git = "nvim-neorg/neorg"
rev = "v9.1.1"

[plugins.vimtex]
git = "lervag/vimtex"
rev = "v2.15"

[plugins."blink.cmp"]
git = "Saghen/blink.cmp"
rev = "v0.10.0"
